services:
  lint:
    build:
      context: ./
      dockerfile: Dockerfile
      target: builder
      args:
        VERSION: "0.56.0"
    command: make lint

  test:
    build:
      context: ./
      dockerfile: Dockerfile
      target: builder
      args:
        VERSION: "0.56.0"
    command: make test

