steps:
- label: ":go: Build & Test"
  key: "test"
  command:
  - "make ci_test"
  agents:
  - "queue=default"
- wait # >
- label: ":docker: Build & Push"
  key: "push"
  # branches:
  # - master
  # depends_on:
  # - test
  command:
  - "make ci_build"
  agents:
  - "queue=default"